# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Get modifiied files
      id: modified-files
      run: |
       MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.js$|\.ts$' || true)
       echo "MODIFIED_FILES=${MODIFIED_FILES}" >> $GITHUB_ENV
    - name: Map to corresponding test files
      id: mapped-tests
      run: |
        TEST_FILES=""
        for FILE in ${MODIFIED_FILES}; do
          TEST_FILE="test/$(basename ${FILE} .js).test.js"
          if [ -f "$TEST_FILE" ]; then
            TEST_FILES="$TEST_FILES $TEST_FILE"
          fi
        done
        echo "TEST_FILES=${TEST_FILES}" >> $GITHUB_ENV
    - name: Run tests on modified files
      if: env.TEST_FILES != ''
      run: |
        echo "Running tests for the following modified files:"
        echo "${TEST_FILES}"
        npm run test -- ${TEST_FILES}